"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getWeaknessName = exports.getWeakness = exports.Weakness = exports.calculateWeaknesses = exports.pokemonTypeMapping = exports.PokemonType = exports.getStatColor = exports.statsMapping = exports.statsKeys = exports.mapStringToTier = exports.mapSmogonTier = exports.SmogonTierKeys = exports.SmogonTierValues = exports.SmogonTier = void 0;
var pokemon_1 = require("./pokemon");
Object.defineProperty(exports, "SmogonTier", { enumerable: true, get: function () { return pokemon_1.SmogonTier; } });
Object.defineProperty(exports, "SmogonTierValues", { enumerable: true, get: function () { return pokemon_1.SmogonTierValues; } });
Object.defineProperty(exports, "SmogonTierKeys", { enumerable: true, get: function () { return pokemon_1.SmogonTierKeys; } });
Object.defineProperty(exports, "mapSmogonTier", { enumerable: true, get: function () { return pokemon_1.mapSmogonTier; } });
Object.defineProperty(exports, "mapStringToTier", { enumerable: true, get: function () { return pokemon_1.mapStringToTier; } });
var stats_1 = require("./stats");
Object.defineProperty(exports, "statsKeys", { enumerable: true, get: function () { return stats_1.statsKeys; } });
Object.defineProperty(exports, "statsMapping", { enumerable: true, get: function () { return stats_1.statsMapping; } });
Object.defineProperty(exports, "getStatColor", { enumerable: true, get: function () { return stats_1.getStatColor; } });
var type_1 = require("./type");
Object.defineProperty(exports, "PokemonType", { enumerable: true, get: function () { return type_1.PokemonType; } });
Object.defineProperty(exports, "pokemonTypeMapping", { enumerable: true, get: function () { return type_1.pokemonTypeMapping; } });
Object.defineProperty(exports, "calculateWeaknesses", { enumerable: true, get: function () { return type_1.calculateWeaknesses; } });
Object.defineProperty(exports, "Weakness", { enumerable: true, get: function () { return type_1.Weakness; } });
Object.defineProperty(exports, "getWeakness", { enumerable: true, get: function () { return type_1.getWeakness; } });
Object.defineProperty(exports, "getWeaknessName", { enumerable: true, get: function () { return type_1.getWeaknessName; } });
